[[constraint]]
  name = "github.com/nats-io/nats.go"
  version = "1.9.1"

[[constraint]]
  name = "github.com/openfaas-incubator/connector-sdk"
  version = "0.5.5"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "0.13.3"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "v0.8.1"

[prune]
  go-tests = true
  unused-packages = true
